apiVersion: v1
kind: Service
metadata:
  name: wordsmith-words
  labels:
    app: wordsmith-words
spec:
  selector:
    app: wordsmith-words
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
