apiVersion: v1
kind: Service
metadata:
  name: wordsmith-db
  labels:
    app: wordsmith-db
spec:
  selector:
    app: wordsmith-db
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  type: ClusterIP
